run-streamlit:
    streamlit run streamlit_app.py

	build-docker-streamlit:
		docker build -t /src/chatbot-ui/streamlit-app .
		
	run-docker-streamlit:
		docker run -p 8501:8501 /src/chatbot-ui/streamlit-app